INSERT INTO acoes (ticker, nome) VALUES
('ABEV3', 'Ambev S.A.'),
('BBDC4', 'Banco Bradesco'),
('BBAS3', 'Banco do Brasil'),
('PETZ3', 'Petz'),
('ASAI3', 'Assaí'),
('LREN3', 'Lojas Renner'),
('CSNA3', 'Siderúrgica Nacional'),
('VVAR3', 'Via Varejo'),
('ELET3', 'Eletrobras'),
('MAGG3', 'Magazine Luiza'),
('GGBR4', 'Gerdau'),
('USIM5', 'Usiminas'),
('HYPE3', 'Hypera'),
('AZUL4', 'Azul Linhas Aéreas'),
('CPLE6', 'Copel'),
('ITSA4', 'Itaúsa'),
('ECOR3', 'Ecorodovias'),
('MRFG3', 'Marfrig'),
('BIDI11', 'Banco Inter'),
('CIEL3', 'Cielo'),

('SULA11', 'SulAmérica'),
('TIMP3', 'TIM Participações'),
('WEGE3', 'Weg'),
('RENT3', 'Localiza'),
('CVCB3', 'CVC Brasil'),
('EGIE3', 'Engie Brasil'),
('RDOR3', 'Rede Dor'),
('BTOW3', 'B2W Digital'),
('MGLU3', 'Magazine Luiza'),
('VIVT3', 'Vivo'),
('BRF3', 'BRF S.A.'),
('RAIL3', 'Rumo'),
('MRVE3', 'MRV Engenharia'),
('IGTA3', 'Iguatemi'),
('ELPL3', 'Eletropaulo'),
('BEEF3', 'Minerva'),
('SEER3', 'Ser Educacional'),
('JBSS3', 'JBS'),
('MYPK3', 'Iochpe-Maxion'),
('GFSA3', 'Gafisa'),
('EVEN3', 'Even Construtora'),
('TCSA3', 'Trisul'),
('PRIO3', 'PetroRio'),
('HGTX3', 'Hering'),
('ENBR3', 'Energias BR'),
('CYRE3', 'Cyrela Brazil Realty'),
('POSI3', 'Positivo Tecnologia'),
('LOGG3', 'Log Commercial Properties'),
('CAML3', 'Camil'),
('QUAL3', 'Qualicorp'),
('CARR3', 'Cairo Americano'),
('MEAL3', 'IMC Mercantil'),
('DOHL4', 'Dohler'),
('CRDE3', 'Cremer'),

('QGEP3', 'Queiroz Galvão'),
('GBIO33', 'Biomm'),
('MDIA3', 'M. Dias Branco'),
('DTEX3', 'Duratex'),
('BRAP4', 'Bradespar'),
('ENEV3', 'Eneva'),
('CSMG3', 'Copasa'),
('UNIP6', 'Unipar Carbocloro'),
('OIBR3', 'Oi'),
('RAPT4', 'Randon Participações'),
('GUAR3', 'Guararapes'),
('MILS3', 'Mills Engenharia'),
('SIMH3', 'Simpar'),
('ODPV3', 'Odontoprev'),
('KLBN11', 'Klabin'),
('GOLL4', 'Gol'),
('BRKM5', 'Braskem'),
('BPAC11', 'BTG Pactual'),
('BRPR3', 'BR Properties'),
('BRAP3', 'Bradespar'),
('PSSA3', 'Porto Seguro'),
('LCAM3', 'Locamerica'),
('MULT3', 'Multiplan'),
('SUZB3', 'Suzano Papel e Celulose'),
('GOAU4', 'Metalúrgica Gerdau'),
('TOTS3', 'Totvs'),
('ABCB4', 'Banco ABC Brasil'),
('GETT11', 'GetNet'),
('RBRF11', 'RB Capital'),
('HBOR3', 'Helbor'),
('BBDC3', 'Bradesco'),
('RDAL3', 'Alper Consultoria e Corretora de Seguros'),
('VBBR3', 'Vibra Energia'),
('TASA4', 'Taurus Armas'),
('ATOM3', 'Atom Empreendimentos e Participações'),
('AMER3', 'Americanas'),
('ALPA4', 'Alpargatas'),
('ALUP11', 'Alupar'),
('AURA33', 'Aura Minerals'),
('B3SA3', 'B3'),
('BBSE3', 'BB Seguridade'),
('BIDI4', 'Banco Inter'),
('BMGB4', 'Banco BMG'),
('BMOB3', 'Bemobi'),
('BOBR4', 'Banese'),
('BRBI11', 'Brasil Brokers'),
('BRKM3', 'Braskem'),
('BRKM6', 'Braskem'),
('BRSR6', 'Banrisul'),
('BRTO3', 'Brasil Telecom'),
('BPAN4', 'Banco PAN'),
('CASH3', 'Méliuz'),
('CEAB3', 'C&A Modas'),
('CESP6', 'CESP'),
('CMIG4', 'Cemig'),
('COGN3', 'Cogna Educação'),
('CPFE3', 'CPFL Energia'),
('CRFB3', 'Carrefour Brasil'),
('CSAN3', 'Cosan'),
('DIRR3', 'Direcional'),
('ENAT3', 'Enauta'),
('ENGI11', 'Engie Brasil'),
('ENJU3', 'Enjoei'),
('EZTC3', 'EZTEC'),
('FESA4', 'Ferbasa'),
('FLRY3', 'Fleury'),
('GGBR3', 'Gerdau'),
('GMAT3', 'Grupo Mateus'),
('GOAU3', 'Metalúrgica Gerdau'),
('IRBR3', 'IRB Brasil Resseguros'),
('ITSA3', 'Itaúsa'),
('ITUB3', 'Itaú Unibanco'),
('JHSF3', 'JHSF Participações'),
('LIGT3', 'Light'),
('LWSA3', 'Locaweb'),
('MOVI3', 'Movida'),
('NEOE3', 'Neoenergia'),
('NTCO3', 'Natura &Co'),
('PETR3', 'Petrobras'),
('RADL3', 'Raia Drogasil'),
('SBSP3', 'Sabesp'),
('SLCE3', 'SLC Agrícola'),
('SMTO3', 'São Martinho'),
('TAEE11', 'Taesa'),
('TIMS3', 'TIM'),
('TRPL4', 'Transmissão Paulista'),
('TUPY3', 'Tupy'),
('USIM3', 'Usiminas'),
('VAMO3', 'Vamos');
