-- Inserção de FIIs
INSERT INTO fiis (ticker, nome, setor) VALUES
('HGLG11', 'CSHG Logística', 'Logística'),
('KNRI11', 'Kinea Renda Imobiliária', 'Renda Imobiliária'),
('MXRF11', 'Maxi Renda', 'Híbrido'),
('VISC11', 'Vinci Shopping Centers', 'Shoppings'),
('BTLG11', 'BTG Logística', 'Logística'),
('HCTR11', 'Hedge TOP FOFII 3', 'Fundo de Fundos'),
('XPML11', 'XP Malls', 'Shoppings'),
('HGRE11', 'CSHG Real Estate', 'Lajes Corporativas'),
('BRCR11', 'BTG Pactual Corporate Office Fund', 'Lajes Corporativas'),
('BCFF11', 'BTG Pactual Fundo de Fundos', 'Fundo de Fundos'),
('RBVA11', 'Rio Bravo Renda Varejo', 'Varejo'),
('XPLG11', 'XP Log', 'Logística'),
('KNIP11', 'Kinea Índices de Preços', 'Títulos e Valores Mobiliários'),
('IRDM11', 'Iridium Recebíveis Imobiliários', 'Recebíveis Imobiliários'),
('HGBS11', 'CSHG Brasil Shopping', 'Shoppings'),
('RBRP11', 'RBR Properties', 'Híbrido'),
('CPTS11', 'Capitânia Securities II', 'Recebíveis Imobiliários'),
('HFOF11', 'Hedge TOP FOFII 2', 'Fundo de Fundos'),
('HSML11', 'Hedge Shopping Malls', 'Shoppings'),
('HGCR11', 'CSHG Recebíveis Imobiliários', 'Recebíveis Imobiliários'),
('RBRR11', 'RBR Rendimento High Grade', 'Recebíveis Imobiliários'),
('VILG11', 'Vinci Logística', 'Logística'),
('XPIN11', 'XP Industrial', 'Industrial'),
('VGIR11', 'Valora RE III', 'Recebíveis Imobiliários'),
('RECT11', 'REC Renda Imobiliária', 'Lajes Corporativas'),
('VGIP11', 'Valora RE II', 'Recebíveis Imobiliários'),
('JPPA11', 'JS Real Estate Multigestão', 'Híbrido'),
('SPTW11', 'SP Downtown', 'Lajes Corporativas'),
('MFII11', 'Merito Desenvolvimento Imobiliário I', 'Desenvolvimento Imobiliário'),
('TORD11', 'Tordesilhas EI', 'Títulos e Valores Mobiliários'),
('BBPO11', 'BB Progressivo', 'Agências Bancárias'),
('KNHY11', 'Kinea High Yield', 'Títulos e Valores Mobiliários'),
('XPPR11', 'XP Properties', 'Lajes Corporativas'),
('BBFI11B', 'BB Fundo de Investimento Imobiliário Progressivo', 'Agências Bancárias'),
('DEVA11', 'Devant Recebíveis Imobiliários', 'Recebíveis Imobiliários'),
('HSML11', 'Hedge Shopping Malls', 'Shoppings'),
('AFCR11', 'AGFI CRI', 'Recebíveis Imobiliários'),
('HGLG11', 'CSHG Logística', 'Logística'),
('HLOG11', 'CSHG Logística', 'Logística'),
('HSRE11', 'Hedge Shopping Renda Educacional', 'Renda Imobiliária');

-- Continue adicionando mais FIIs conforme necessário
